language: node_js

matrix:
  include:
    - node_js: '8.9'
      env:
        - DISABLE_INTEGRATION_TESTS=true
    - node_js: '10.6'
    - node_js: '10.6'
      env:
        - DISABLE_INTEGRATION_TESTS=true
        - DISABLE_UNIT_TESTS=true
        - LINTING=true

sudo: false

install:
  - travis_retry npm install

script:
  - if [[ -z "$DISABLE_UNIT_TESTS" ]]; then npm run test; fi
  - if [[ ! -z "$LINTING" ]]; then npm run lint; fi
  - if [[ -z "$DISABLE_INTEGRATION_TESTS" ]]; then npm run integration-test; fi

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage